#!/usr/bin/env bash
#
# install.sh — make e2e-ai-kit usable from any substrate project.
#
# What it does (mirrors theplant/maint-ai-tools' clone+symlink model):
#   1. installs the kit's own dependencies (tsx, yaml) ONCE, here in the clone
#   2. symlinks every skill under skills/ into ~/.claude/skills/ (global)
#   3. generates a global `e2e-ai-kit` command that runs the lint CLI FROM
#      THIS CLONE — so a substrate never needs to know where the kit lives,
#      and never has to install tsx/yaml itself.
#
# Update later with `git pull` in this clone — symlinks + wrapper keep working.

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$HOME/.claude/skills"
BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/e2e-ai-kit"

# 1. Dependencies — only if missing, so re-running is cheap.
if [ ! -x "$REPO_DIR/node_modules/.bin/tsx" ]; then
    echo "installing kit dependencies (tsx, yaml) ..."
    if command -v yarn >/dev/null 2>&1; then
        (cd "$REPO_DIR" && yarn install --silent)
    else
        (cd "$REPO_DIR" && npm install --no-audit --no-fund --silent)
    fi
else
    echo "deps: ok (tsx present)"
fi

# 2. Symlink skills into the global skills dir.
mkdir -p "$SKILLS_DIR"
for skill_path in "$REPO_DIR/skills"/*/; do
    skill_name="$(basename "$skill_path")"
    target="$SKILLS_DIR/$skill_name"
    if [ -L "$target" ]; then
        echo "skill skip (already linked): $skill_name"
    elif [ -e "$target" ]; then
        echo "skill skip (exists, not a symlink): $skill_name — remove it manually to replace"
    else
        ln -s "$skill_path" "$target"
        echo "skill installed: $skill_name"
    fi
done

# 2b. Symlink contracts so skills' `../../contracts/...` links resolve.
#     From ~/.claude/skills/<name>/ the link `../../contracts` points at
#     ~/.claude/contracts — so link the clone's contracts there.
contracts_target="$HOME/.claude/contracts"
if [ -L "$contracts_target" ]; then
    echo "contracts skip (already linked)"
elif [ -e "$contracts_target" ]; then
    echo "contracts skip (exists, not a symlink) — remove it manually to replace"
else
    ln -s "$REPO_DIR/contracts" "$contracts_target"
    echo "contracts linked: $contracts_target -> this clone"
fi

# 3. Generate the global `e2e-ai-kit` command. The clone path is baked in,
#    so the wrapper works from any CWD and survives the kit being anywhere.
mkdir -p "$BIN_DIR"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by e2e-ai-kit/install.sh — do not edit; re-run install.sh to regenerate.
exec "$REPO_DIR/node_modules/.bin/tsx" "$REPO_DIR/bin/e2e-ai-kit.js" "\$@"
EOF
chmod +x "$WRAPPER"
echo "command installed: $WRAPPER -> this clone"

echo ""
echo "done."
echo ""
case ":$PATH:" in
    *":$BIN_DIR:"*) echo "PATH: ok ($BIN_DIR is on PATH)" ;;
    *) echo "ACTION NEEDED: add $BIN_DIR to your PATH, e.g. add to ~/.zshrc:"
       echo "    export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac
echo ""
echo "Then from any substrate project:"
echo "    e2e-ai-kit lint case tests/cases/<feature>.md"
echo "    e2e-ai-kit lint app-context"
echo "    e2e-ai-kit lint slot"
echo ""
echo "Update later:  cd $REPO_DIR && git pull   (no reinstall needed)"
